"""CLI entry point for running LLM-based financial market simulation experiments.

Supports multiple experiment modes (all-neutral, fixed-bearish-neutral, random, etc.),
batch inference across OpenAI / Anthropic / Google models, adversarial attack injection,
and prompt-hardening mitigations. Results are written to CSV and per-response JSON files
under the specified output directory.

Usage:
    python src/main.py <experiment-type> <news-dir> [options]
    python src/main.py --help
"""
import logging
import argparse
from typing import Optional, Dict, List
from pathlib import Path
from datetime import datetime
import os
import time
import json
from tqdm import tqdm
import litellm
from litellm import completion, completion_cost, batch_completion
from model.llm import LLM
from record_results import ResultsRecorder
from experiments.experimental_run import *
from experiments.episode import Article, AssetType

INFERENCE_MODELS_NAME_MAP: Dict[str, str] = {"openai/gpt-5-mini":"gpt-5-mini", "anthropic/claude-3-5-haiku-20241022":"claude-3.5","gemini/gemini-flash-lite-latest":"gemini-latest"}
ARTICLE_MODELS_NAME_MAP: Dict[str, str] = {"openai/gpt-5-mini":"gpt-5-mini", "anthropic/claude-sonnet-4-5-20250929":"claude-4.5","gemini/gemini-flash-latest":"gemini-full-latest"}
EXPERIMENT_TYPE_MAP: Dict[str, ExperimentalRun] = {
    "random": RandomSentimentRun,
    "random-bullish": RandomBullishBearishRun,
    "fixed-bullish": FixedBullishBearishRun,
    "fixed-bearish-neutral": FixedBearishNeutralRun,
    "all-neutral": AllNeutralRun
}

def setup_logging(output_dir: str):

    log_dir = os.path.join(output_dir, "logs")
    os.makedirs(log_dir, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = os.path.join(log_dir, f"experiment_{timestamp}.log")
    
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(log_file),
            logging.StreamHandler()          # Log to console
        ]
    )
    
    logging.info(f"Logging to: {log_file}")
    return log_file

def parse_args():
    parser = argparse.ArgumentParser(description="Run LLM portfolio allocation experiments")

    parser.add_argument(
        "experiment_type",
        choices=list(EXPERIMENT_TYPE_MAP.keys()),
        help="Type of experiment to run (default: random)"
    )

    parser.add_argument(
        "news_dir",
        help="Directory containing generated news articles and metadata"
    )
    
    parser.add_argument(
        "--inference-models", 
        nargs="+", 
        default=list(INFERENCE_MODELS_NAME_MAP.keys()),
        help="List of models to test response generation (default: %(default)s)"
    )

    parser.add_argument(
        "--allowed-article-models",
        nargs="+",
        default=["openai/gpt-5-mini"],
        help="Filter articles to only those generated by models (default: %(default)s)"
    )

    parser.add_argument(
        "--fixed-assets",
        nargs="+",
        choices=["Equities", "Corporate Bonds", "Government Bonds", "Mortgages Backed Securities"],
        help="Assets that should be fixed for FixedBullishBearishRun or FixedBearishNeutralRun"
    )
    
    parser.add_argument(
        "--num-episodes",
        type=int,
        default=50,
        help="Number of episodes to generate (default: %(default)s)"
    )
    
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility (default: %(default)s)"
    )

    parser.add_argument(
        "--output-dir",
        default="./responses/",
        help="directory to store output file csv, logs & parameters (default: %(default)s)"
    )
    
    parser.add_argument(
        "--results-file-basename",
        default="results.csv",
        help="Output file basename for results (default: %(default)s); joined with output dir above"
    )

    parser.add_argument(
        "--batch-mode",
        action="store_true",
        help="If option is provided, use batch API requests instead of synchronous calls",
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=25,
        help="Number of episodes that should constitute a batch, in batch mode"
    )

    parser.add_argument(
        "--attack-config",
        type=str, 
        help="Path to JSON file with attack configuration"
    )

    parser.add_argument(
        "--mitigations",
        nargs="+",
        type=str, 
        default=None,
        help="Mitigations to run LLM with"
    )

    parser.add_argument(
        "--experiment-tag",
        help="Custom tag to apply to experiment run names (default: %(default)s)"
    )        
    return parser.parse_args()

def create_experiment(experiment_type: str, 
                      news_dir: str,
                      num_episodes: int, seed: int, 
                      allowed_models: Optional[List[str]], 
                      fixed_assets: Optional[List[AssetType]] = None,
                      insertion_config: Optional[Dict[str, Any]] = None,
                      tag: Optional[str] = None) -> ExperimentalRun:
    
    
    model_strs = "--".join([ARTICLE_MODELS_NAME_MAP[model_full_str] for model_full_str in allowed_models])
    experiment_name = f"experiment-{experiment_type}__article_models-{model_strs}__seed-{seed}"

    if experiment_type == "fixed-bullish":
        assets_for_name = fixed_assets if fixed_assets else [DEFAULT_BULLISH_ASSET]
        bullish_str = "--".join(["-".join((asset.value).split(" ")) for asset in assets_for_name])
        experiment_name += f"__bullish-{bullish_str}"

    if experiment_type == "fixed-bearish-neutral":
        assets_for_name = fixed_assets if fixed_assets else [DEFAULT_BEARISH_ASSET]
        bearish_str = "--".join(["-".join((asset.value).split(" ")) for asset in assets_for_name])
        experiment_name += f"__bearish-{bearish_str}"
    
    if insertion_config:
        attack_str = f"{insertion_config['attack_type']}--{insertion_config['target_asset'].replace(' ', '-')}"
        experiment_name += f"__attack-{attack_str}"

    if tag is not None: 
        experiment_name += f"__tag-{tag}"

    experiment_class = EXPERIMENT_TYPE_MAP.get(experiment_type)
    if not experiment_class:
        raise ValueError(f"Unknown experiment type: {experiment_type}")
    
    return experiment_class.generate_run_from_dir(
            name=experiment_name,
            source_news_dir=news_dir,
            num_episodes=num_episodes,
            seed=seed,
            allowed_models=allowed_models,
            fixed_assets=fixed_assets,
            insertion_config=insertion_config
        )
    
def run_experiment_on_models(experiment: ExperimentalRun, inference_models: List[str], 
                             recorder: ResultsRecorder, mitigations: Optional[List[str]] = None):
    total_cost = 0.0
    
    for model in inference_models:
        logging.info(f"Running experiment on model: {model}")
        llm = LLM(model=model, mitigations=mitigations)
        
        for episode_idx, episode in enumerate(tqdm(experiment.episodes, desc=f"{model}")):
            logging.info(f"Processing episode {episode_idx + 1}/{len(experiment.episodes)} for {model}")

            try:
                # response, response_cost = llm.run_with_article_filepaths(article_paths)
                response, response_cost = llm.run_with_episode(episode)

                recorder.record_result(
                    episode = episode, 
                    model = model,
                    response = response, 
                    episode_cost = response_cost,
                    mitigations = mitigations
                )

                logging.info(f"Processed episode {episode_idx + 1}/{len(experiment.episodes)} for {model}")

            except Exception as e:
                logging.error(f"Error processing episode {episode_idx + 1} with model {model}: {e}")
                continue

        total_cost += llm.cost
        logging.info(f"Completed {model} - Model Cost: ${llm.cost:.4f}")
    
    logging.info(f"Total experiment cost: ${total_cost:.4f}")


def run_experiment_on_models_batch(
    experiment: ExperimentalRun,
    inference_models: List[str],
    recorder: ResultsRecorder,
    batch_size: int = 25,
    mitigations: Optional[List[str]] = None
):
        
    for model in inference_models:
        logging.info(f"Running batch inference with model: {model}")
        logging.info(f"Processing {len(experiment.episodes)} episodes in batches of {batch_size}")
        
        llm = LLM(model=model, mitigations=mitigations)
        
        total_episodes = len(experiment.episodes)
        num_batches = (total_episodes + batch_size - 1) // batch_size
        
        for batch_idx,_ in enumerate(tqdm(range(num_batches),desc=f"{model}")):
            start_idx = batch_idx * batch_size
            end_idx = min(start_idx + batch_size, total_episodes)

            logging.info(f"Processing Model {model} - Batch {batch_idx + 1}/{num_batches} "
            f"(episodes {start_idx + 1}-{end_idx})")
            batch_episodes = experiment.episodes[start_idx:end_idx]

            try:
                responses, response_costs = llm.run_batch_with_episodes(batch_episodes)
                
                for episode, response, response_cost in zip(batch_episodes, responses, response_costs):
                    if response is None:
                        logging.error(f"Model {model} - Skipping episode {episode.id} due to failed response")
                        continue
                    
                    recorder.record_result(
                        episode=episode,
                        model=model,
                        response=response,
                        episode_cost=response_cost,
                        mitigations=mitigations
                    )
                
                successful = sum(1 for r in responses if r is not None)
                logging.info(f"Model - {model}"
                            f"Completed batch {batch_idx + 1}/{num_batches}. "
                            f"Successful: {successful}/{len(batch_episodes)}, "
                            f"Batch cost: ${sum(response_costs):.4f}")
                
            except Exception as e:
                # Catch catastrophic failures (not rate limits - those are handled internally)
                logging.error(f"Fatal error processing model {model} - batch {batch_idx + 1}: {type(e).__name__}: {e}")
                logging.error(f"Skipping batch and continuing with next")
                continue
        
        logging.info(f"Completed all batches for {model}. "
                    f"Total cost: ${llm.get_total_cost():.4f}")
        logging.info(f"Average cost per episode: ${llm.get_total_cost() / total_episodes:.4f}")


def main():
    args = parse_args()
    print(args.allowed_article_models)
    output_dir = args.output_dir

    if not Path(output_dir).exists():
        os.makedirs(output_dir)

    log_file = setup_logging(output_dir)

    if not Path(args.news_dir).exists():
        logging.error(f"News directory not found: {args.news_dir}")
        raise FileNotFoundError(f"News directory not found: {args.news_dir}")
    
    print("Fixed assets arg:", args.fixed_assets)
    fixed_assets = None
    if args.fixed_assets:
        fixed_assets = [AssetType(asset) for asset in args.fixed_assets]
    print("Fixed assets after :", fixed_assets)

    
    insertion_config = None
    if args.attack_config:
        with open(args.attack_config, 'r') as f:
            insertion_config = json.load(f)

    logging.info(f"Creating {args.experiment_type} experiment with {args.num_episodes} episodes")
    experiment = create_experiment(
        experiment_type=args.experiment_type,
        news_dir=args.news_dir,
        num_episodes=args.num_episodes,
        seed=args.seed,
        allowed_models=args.allowed_article_models,
        fixed_assets=fixed_assets,
        insertion_config=insertion_config,
        tag=args.experiment_tag
        )
    
    excluded_log_fields = {"episodes","available_articles"}
    logging.info(f"Produced experimental run with parameters: {experiment.model_dump_json(exclude=excluded_log_fields)}")

    experiment_definition_fp = os.path.join(output_dir, f"experiment_def_{experiment.id}.json")
    experiment.save_definition(experiment_definition_fp)
    logging.info(f"Experiment definition saved to: {experiment_definition_fp}")
    
    recorder = ResultsRecorder(experimental_run=experiment,
                               results_output_dir=output_dir,
                               csv_basename=args.results_file_basename)
    
    logging.info(f"Running experiment on models: {args.inference_models}")
    if args.batch_mode:
        logging.info(f"Experiment episodes being batch processed!")
        run_experiment_on_models_batch(experiment = experiment,
                                       inference_models = args.inference_models,
                                       recorder = recorder,
                                       batch_size= args.batch_size,
                                       mitigations = args.mitigations)
                
    else:
        logging.info(f"Experiment episodes being sequentially processed!")
        run_experiment_on_models(experiment = experiment,
                                inference_models = args.inference_models,
                                recorder = recorder,
                                mitigations = args.mitigations)
    
    logging.info(f"Experiment completed. Results saved to: {recorder.csv_file_path}")

if __name__ == "__main__":
    main()
